#BungeeCord Proxy Ip
BungeeCord-Ip: 
- 192.168.1.1
- 192.168.1.2
#Message players see when trying to join
Kick-Message: '&a&lPlease join the main server at&6: &5&l173.24.614.214'
#Pardoned UUIDs
Pardons:
- 54321
- 12345